name: Build & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install NPM packages
      run: npm install
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build Application
      run: npm run build
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Image to GH-Pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npx gh-pages -d build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
